export const IPC = {
  GET_STATE: 'launcher:get-state',
  SELECT_INSTANCE: 'launcher:select-instance',
  UPDATE_INSTANCE: 'launcher:update-instance',
  OPEN_FOLDER: 'launcher:open-folder',
  OPEN_LOG_MODAL: 'launcher:open-log-modal',
  CLEAR_LOG: 'launcher:clear-log',
  SAVE_LOG: 'launcher:save-log',
  SET_RAM: 'launcher:set-ram',
  CLEAN_CACHE: 'launcher:clean-cache',
  CLEANUP: 'launcher:cleanup',
  LAUNCH: 'launcher:launch',
  KILL: 'launcher:kill',
  ON_LOG: 'launcher:on-log',
  ON_STATE: 'launcher:on-state',
  ACCOUNTS_LIST: 'accounts:list',
  ACCOUNTS_ACTIVE: 'accounts:active',
  ACCOUNTS_SET_ACTIVE: 'accounts:set-active',
  ACCOUNTS_REMOVE: 'accounts:remove',
  ACCOUNTS_RENAME: 'accounts:rename',
  ACCOUNTS_ADD_OFFLINE: 'accounts:add-offline',
  ACCOUNTS_ADD_MICROSOFT: 'accounts:add-microsoft',
  ACCOUNTS_ADD_AZAUTH: 'accounts:add-azauth',
  ACCOUNTS_STORE_PATH: 'accounts:store-path',
  PROXY_STATUS: 'launcher:proxy-status',
  PROXY_RESTART: 'launcher:proxy-restart',
  PROXY_STOP: 'launcher:proxy-stop',
  CHECK_UPDATE: 'launcher:check-update',
  APPLY_UPDATE: 'launcher:apply-update',
  REPAIR_CHECK: 'launcher:repair-check',
  REPAIR_FIX: 'launcher:repair-fix',
  ACCOUNTS_SET_ACTIVE_FOR_LAUNCH: 'accounts:set-active-for-launch',
} as const;

export type IpcChannel = typeof IPC[keyof typeof IPC];
